server:
  port: 9090
  servlet:
    context-path: /msa-kafka
spring:
  jpa:
    hibernate.ddl-auto: none
    show-sql: true
    database: oracle
  datasource:
    url: jdbc:oracle:thin:@localhost:1521:ORCL
    username: C##PRU
    password: Maicol16.
    driver-class-name: oracle.jdbc.OracleDriver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      pool-name: msa-autorizaciones-batch